name: GetAdult deployment

on:
  push:
    branches: [ "main" ]

env:
  SERVICE_NAME: getadult
  RESOURCE_GROUP: rg-microservice
  IMAGE_BASE_NAME: raulcv/getadult
  ENVIRONMENT_NAME: env-microservice
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    name: Get Adult deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/microservices/GetAdult
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - name: Install az containerapp extension
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Build Docker NET image
        run: | 
          docker build --platform linux -t $IMAGE_BASE_NAME:$IMAGE_TAG -t $IMAGE_BASE_NAME:latest .
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker NET image
        run: |
          docker push $IMAGE_BASE_NAME:latest
          docker push $IMAGE_BASE_NAME:$IMAGE_TAG

      - name : Cleanup old local docker images on the runner
        run: |
          docker image prune -a -f

      - name: Docker Hub Cleanup Old Images
        working-directory: ${{ github.workspace }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          REPOSITORY: $IMAGE_BASE_NAME
          KEEP_LAST: 3
        run: |
          ls -l infrastructure/
          chmod +x ./infrastructure/dockerhub-cleanup.sh
          ./infrastructure/dockerhub-cleanup.sh

      - name: Deploy Container App
        run: |
          az containerapp up --name $SERVICE_NAME --image $IMAGE_BASE_NAME:$IMAGE_TAG \
          --resource-group $RESOURCE_GROUP --environment $ENVIRONMENT_NAME  \
          --env-vars SQL_CONNECTION_STRING="${{secrets.SQL_CONNECTION_STRING}}" \
          --ingress external --target-port 8080 --debug
