name: PickAge deployment

on:
  push:
    branches: [ "main" ]

env:
  SERVICE_NAME: pickage
  RESOURCE_GROUP: rg-microservice
  IMAGE_BASE_NAME: raulcv/pickage:latest
  ENVIRONMENT_NAME: env-microservice

jobs:
  build-and-deploy:
    name: Pick age deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/microservices/PickAge
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - name: Install az containerapp extension
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Build Docker NET image
        run: | 
          docker build --platform linux --tag $IMAGE_BASE_NAME .
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker NET image
        run: |
          docker push $IMAGE_BASE_NAME

      - name: Check Docker image version
        run: |
          IMAGE_VERSION=$(docker image inspect --format='{{.RepoDigests}}' $IMAGE_BASE_NAME)
          echo "Docker image version: $IMAGE_VERSION"

      - name: Deploy Container App
        run: |
          az containerapp up --name $SERVICE_NAME --image $IMAGE_BASE_NAME \
          --resource-group $RESOURCE_GROUP --environment $ENVIRONMENT_NAME  \
          --env-vars SERVICEBUS_CONNECTION_STRING="${{secrets.SERVICEBUS_CONNECTION_STRING}}" SERVICEBUS_QUEUE_NAME="${{secrets.SERVICEBUS_QUEUE_NAME}}"
